# Generated by Django 4.2.3 on 2023-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='image.jpg', null=True, upload_to='images/'),
        ),
    ]
