# Generated by Django 4.2.3 on 2023-08-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_age_profile_city_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fees',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
