# Generated by Django 4.2.3 on 2023-08-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_mobile_profile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
    ]
